---
# tasks file for cvmfs-server

- name: Ensure OS prerequisies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ prerequisites[ ansible_os_family | lower ]}}"

- include: "install-{{ ansible_os_family | lower }}.yml"

- include: repo.yml
